 ---
- name: Dlink  Standard Configuration
  hosts: switches
  gather_facts: false
  connection: network_cli
     
# Configuring..... 
# Hostname
# Enabling Spanning Tree
# Disabling Telnet
# Disabling HTTP
# Configuring NTP Services
# Creating User
# Enabling syslog
# Creating VLAN499 for LAN1

  tasks:
    - name: Dlink  Global Settings
      ios_config:
        lines:
          - snmp-server name {{inventory_hostname}}
          - spanning-tree global state enable
          - no ip telnet server
          - no ip http server
          - clock timezone + 5 30
          - sntp enable
          - no sntp server 10.90.90.100
          - sntp server 216.239.35.4
          - username test password test123
          - username test privilege 15
          - logging on
          - logging buffered severity 7 write-delay 3
          - vlan 499
         
      register: print_output

    - debug: var=print_output

# Configuring...
# Changing ports mode to access
# Confguring Switch-port Security
# Making Access ports Member of VLAN 10

    - name: Access port configuration
      ios_config:
        parents: interface ethernet 1/0/1
        lines:
           - switchport mode access
           - switchport port-security
           - switchport port-security maximum 1
           - switchport port-security mode permanent
           - switchport port-security violation protect
           - switchport access vlan 499         
      
      register: print_output

    - debug: var=print_output

#configuring AP uplink port
#Chaning ports mode to trunk
#Configured description

    - name: Configuring AP port as Trunk
      ios_config:
        parents: interface ethernet 1/0/17
        lines:
           - switchport mode trunk
           - description **Connected to AP**

      register: print_output

    - debug: var=print_output

#configuring GPON uplink port
#Changing ports mode to trunk
#configured description

    - name: Configuring uplink port connected to GPON
      ios_config:
        parents: interface ethernet 1/0/25
        lines:
           - switchport mode trunk
           - description **Connected to GPON**

      register: print_output

    - debug: var=print_output

#Configuring storm control on all accessport
    - name: Enabing storm control on port 1-24
      ios_config:
        parents: interface range ethernet 1/0/1-24
        lines: 
           - storm-control action drop
           - storm-control broadcast level kbps 5000
           - storm-control multicast level kbps 5000
           - storm-control unicast level kbps 5000

      register: print_output
    - debug: var=print_output

#Cnfiguring default route towards gateway
    - name: Configuring default route toward's gateway
      ios_config:
        lines: 
           - ip route 0.0.0.0 0.0.0.0 10.90.90.91

      register: print_output
    - debug: var=print_output
 
#Saving running-config to startup-config

    - name: saving running to startup config when modified
      ios_command:
          commands:
          - command: 'copy running-config startup-config'
            prompt: 'Destination filename startup-config?'
            answer: 'y'

      register: print_output

    - debug: var=print_output

#Verifying configuration through startup config

    - name: Get changed config for D-Link switches
      ios_command:
        commands:
           - show startup
        

      register: print_output

    - debug: var=print_output.stdout_lines

